### ISSUE TITLE
ember-cli-typescript version outdated

### ISSUE THREAD

**Issue by sebastianhelbig** [mirego/ember-best-language#16]
>WARNING: The 'ember-best-language' addon is using an older version of ember-cli-typescript that uses stage 1 decorators. Please update to ember-cli-typescript@v2 to remove your dependency on legacy decorators.

**Comment by spikying** [comment]
+1

**Comment by charlesdemers** [comment]
Hi! `ember-best-language` uses both TypeScript and decorators that’s why the message is appearing. This is a bit annoying for us because `ember-cli-typescript` v2 is still in beta/RC, so we don't want to update right away… I don’t know why they prompt users to update to an unstable version 🤔

We plan to update the addon to v2 as soon as it's released as a "stable" version. In the meantime, I’m trying to make it work with the Release Candidate version, I'll let you know when I have something!

**Comment by scottkidder** [comment]
Just bumping this because ember-cli-typescript 2 has been released :tada:

**Comment by charlesdemers** [comment]
A new version was released to fix this, please install version 1.0.4 to get the update
