### ISSUE TITLE
IE 11 Error

### ISSUE THREAD

**Issue by basz** [mirego/ember-best-language#38]
An error in IE happens...

https://github.com/mirego/ember-best-language/blob/e4e43583883ca7d2b0f3b3cf7d33522c0c52ecaa/addon/services/best-language.ts#L66

`new Set()` works, but `new Set(mySet)` is not supported by IE11. 

```js
const set = new Set();
languages.forEach(lang => set.add(lang));
languages = Array.from(languages);
```

but if the uniqueness is the purpose this might be nicer

```js
languages.filter((val, i, arr) => arr.indexOf(val) === i).
```

https://caniuse.com/#feat=mdn-javascript_builtins_set_set_iterable_allowed

**Comment by charlesdemers** [comment]
@basz Thanks for reporting! You can update to 2.0.3 to get the new version with the fix. Cheers!

**Comment by basz** [comment]
Hi Thanks for your fix... 

Just wanted to say older Edge versions still crash apps on an unsupported es6 feature. the object spread notation is not supported in Edge Legacy. 

https://caniuse.com/#feat=mdn-javascript_operators_spread_spread_in_object_literals

**Comment by charlesdemers** [comment]
@basz We support IE11 in most of our apps at Mirego and Babel usually takes care of compiling this stuff down to ES5 with a polyfill for `Object.assign`. Maybe the app recompiles the addon to support legacy targets? 🤔 

I think maybe I can configure TypeScript to output ES5 instead of modern JS, I’ll need to investigate. In the meantime, if you could tell me a bit about your setup that would help to reproduce the bug. Thanks!
